### ISSUE TITLE
The GNOME 42 runtime is no longer supported as of March 21, 2023

### ISSUE THREAD

**Issue by jianpan** [flathub/com.amazon.Workspaces#32]
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.amazon.Workspaces

**Comment by bbhtt** [comment]
See https://github.com/flathub/com.amazon.Workspaces/pull/27#issue-1396308485, not sure if it's going to work with >=42. It'd be nice if you are able to confirm

**Comment by compuguy** [comment]
FYI @bbhtt the build in the pull request from March is no longer accessible.

**Comment by bbhtt** [comment]
The logs in https://github.com/flathub/com.amazon.Workspaces/pull/27#issuecomment-1636125648 indicate that due to missing webkitgtk2-4.0 the program refuses to run:

```
/app/extra/bin/libwebkit2gtk-4.0.so.37.so: cannot open shared object file: No such file or directory
/app/extra/bin/liblibwebkit2gtk-4.0.so.37.so: cannot open shared object file: No such file or directory
/app/extra/bin/libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
/app/extra/bin/liblibwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```
We unfortunately can't bundle it here.

webkitgtk2-4.0 (built with libsoup2 was removed from runtime 43 onwards). Until Amazon updates that dependency by porting the client to webkitgtk2-4.1 (using libsoup3) I can't update the runtime to >=43. 

I suggest using the feedback form in the program (Support > Feedback) to let Amazon know.

**Comment by AsciiWolf** [comment]
@bbhtt See how I handled this in Xiphos: https://github.com/flathub/org.xiphos.Xiphos/pull/11/files#diff-1bf280b4e00cd6a99da872ca9c50d807034c22b1bb37fc285c48ceb2e480a84bR187

**Comment by jianpan** [comment]
Thanks! It works for me. But the clipboard integration still isn't working.

com.amazon.Workspaces            4.6.0.4187
 org.gnome.Platform/x86_64/44

**Comment by bbhtt** [comment]
> But the clipboard integration still isn't working.

I'll need to investigate it more. If you can share the logs in the other issue we talked about, it'd be helpful.

The new build with runtime 44 will be published in 4–5 hours. You can remove the test build and do a `flatpak update` to update.
